// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fxwsaxvzeguruaiibhvo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ4d3NheHZ6ZWd1cnVhaWliaHZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzcwNzU2NTYsImV4cCI6MjA1MjY1MTY1Nn0.CFhQzssOAlQ6___cGoK5-mJR2ZGfzz0Rk_I1dSEuNbk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);